# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 22:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apt_date', models.DateTimeField(verbose_name='appointment date')),
                ('location', models.CharField(max_length=200)),
                ('in_doctor_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('phone_number', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_name', models.CharField(default='defaultward', max_length=200)),
                ('room_number', models.IntegerField(default=0)),
                ('bed_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalStaff',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='registrations.Person')),
                ('employee_number', models.IntegerField(default=11111)),
                ('login_password', models.CharField(max_length=20)),
            ],
            bases=('registrations.person',),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='registrations.Person')),
                ('patient_number', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('insurance_number', models.IntegerField(default=0)),
                ('reg_date', models.DateTimeField(verbose_name='date registered')),
                ('ext_doctor_id', models.IntegerField(default=0)),
                ('rationale', models.CharField(max_length=200)),
                ('priority', models.IntegerField(default=0)),
            ],
            bases=('registrations.person',),
        ),
        migrations.AddField(
            model_name='ward',
            name='medical_staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registrations.MedicalStaff'),
        ),
        migrations.AddField(
            model_name='patient',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrations.Ward'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrations.Patient'),
        ),
    ]
